apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "litecoin.fullname" . }}
  labels:
    {{- include "litecoin.labels" . | nindent 4 }}
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi