apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "litecoin.fullname" . }}
  labels:
    {{- include "litecoin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "litecoin.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "litecoin.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "litecoin.selectorLabels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "litecoin.selectorLabels" . | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "litecoin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: litecoinData
              mountPath: /home/litecoin
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15 #Default 0
            periodSeconds: 30 #Default 10
            timeoutSeconds: 5 #Default 1
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15 #Default 0
            periodSeconds: 30 #Default 10
            timeoutSeconds: 5 #Default 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumes:
    - name: litecoinData
      persistentVolumeClaim:
        claimName: {{ include "litecoin.fullname" . }}